order/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import OrderEachView, OrderProductAddView, OrderItemDeleteView, OrderCloseView, OrderDeleteView, \
    OrderEditView, OrderPaymentCreate, OrderPaymentDeleteView, OrderList, OrderPenaltyAdd, OrderPenaltyDelete


urlpatterns = [
    path('each/<int:pk>', login_required(OrderEachView.as_view()), name='each'),
    path('list/', login_required(OrderList.as_view()), name='list'),
    path('penalty_delete/<int:pk>', login_required(OrderPenaltyDelete.as_view()), name='penalty-delete'),
    path('penalty_add/<int:pk>', login_required(OrderPenaltyAdd.as_view()), name='penalty-add'),
    path('product-add/', login_required(OrderProductAddView.as_view()), name='product-add'),
    path('product-delete/<int:pk>', login_required(OrderItemDeleteView.as_view()), name='product-delete'),
    path('close/<int:pk>', login_required(OrderCloseView.as_view()), name='close'),
    path('delete/<int:pk>', login_required(OrderDeleteView.as_view()), name='delete'),
    path('edit/<int:pk>', login_required(OrderEditView.as_view()), name='edit'),
    path('payment-create/', login_required(OrderPaymentCreate.as_view()), name='payment-create'),
    path('payment-delete/<int:pk>', login_required(OrderPaymentDeleteView.as_view()), name='payment-delete'),
]

paymentlog/urls.py
from django.urls import path
from .views import PaymentLogDeleteView, payment_log_view
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('list/', login_required(payment_log_view), name='list'),
    path('delete/<int:pk>', login_required(PaymentLogDeleteView.as_view()), name='delete'),
]

sauna/urls.py
from django.urls import path
from .views import CalendarView, LoginView, LogoutView, OrderAddView, get_sauna_type_ajax, ChangePassword
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', login_required(LogoutView.as_view()), name='logout'),
    path('pass_change/<int:pk>', login_required(ChangePassword.as_view()), name='password_change'),
    path('sauna/', login_required(CalendarView.as_view()), name='calendar_view'),
    path('order/add/', login_required(OrderAddView.as_view()), name='order-add'),
    path('sauna_type_ajax/', login_required(get_sauna_type_ajax), name='get_sauna_type_ajax'),
]

system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('sauna.urls', 'sauna'), namespace='sauna')),
    path('client/', include(('client.urls', 'client'), namespace='client')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('payment-log/', include(('paymentlog.urls', 'paymentlog'), namespace='payment_log')),
    path('outlay/', include(('outlay.urls', 'outlay'), namespace='outlay')),
]

paymentlog/models.py
from django.db import models
from django.contrib.auth.models import User
from .choices import PAYMENT_TYPE, PAYMENT_METHOD
from order.models import Order
from datetime import datetime, date


class PaymentLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    amount = models.IntegerField()
    discount = models.IntegerField(default=0, blank=True, null=True)
    total = models.IntegerField()
    payment_type = models.CharField(max_length=500, choices=PAYMENT_TYPE, default='advance', verbose_name='Тип оплаты')
    payment_method = models.CharField(max_length=500, choices=PAYMENT_METHOD, default='cash', verbose_name='Метод оплаты')
    comment = models.CharField(max_length=500)
    # created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    created = models.DateTimeField(default=date.today().today(), verbose_name='Дата создания')

paymentlog/forms.py
from django import forms
from .models import PaymentLog


class PaymentLogForm(forms.ModelForm):
    class Meta:
        model = PaymentLog
        fields = ('payment_type', 'payment_method')

paymentlog/views.py
from django.shortcuts import render
from outlay.models import Outlay
from django.core.paginator import Paginator
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from .models import PaymentLog
from django.db.models import Sum
from datetime import date, datetime
from .filters import PaymentLogFilters


# class PaymentLogView(ListView):
#     model = PaymentLog
#     template_name = 'paymentlog.html'
#     paginate_by = 10
#
#     def get_queryset(self):
#         qs = super().get_queryset()
#         qs = PaymentLogFilters(self.request.POST, queryset=qs)
#         return qs
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data()
#         cash = PaymentLog.objects.filter(payment_method='cash', created=datetime.today().strftime('%Y-%m-%d'))
#         cashless = PaymentLog.objects.filter(payment_method='cashless', created=datetime.today().strftime('%Y-%m-%d'))
#         cashless_count = cashless.count()
#         cashless_sum = cashless.aggregate(sum=Sum('amount'))['sum']
#         cash_count = cash.count()
#         cash_sum = cash.aggregate(sum=Sum('amount'))['sum']
#         context['cash_count'] = cash_count
#         context['cash_sum'] = cash_sum
#         context['cashless_count'] = cashless_count
#         context['cashless_sum'] = cashless_sum
#         context['today'] = datetime.today
#         context['filter'] = PaymentLogFilters
#         if cash_sum is None:
#             cash_sum = 0
#         if cashless_sum is None:
#             cashless_sum = 0
#         context['total_sum'] = int(cash_sum) + int(cashless_sum)
#         return context


def payment_log_view(request):
    today = date.today()
    cash = PaymentLog.objects.filter(payment_method='cash', created=today.today())
    cashless = PaymentLog.objects.filter(payment_method='cashless', created=today.today())
    outlay_for_today = Outlay.objects.filter(created=datetime.today().strftime('%Y-%m-%d'))
    outlay_sum = outlay_for_today.aggregate(sum=Sum('summa'))['sum']
    cashless_count_ = cashless.count()
    cashless_sum_ = cashless.aggregate(sum=Sum('amount'))['sum']
    cash_count_ = cash.count()
    cash_sum_ = cash.aggregate(sum=Sum('amount'))['sum']
    cash_count = cash_count_
    cash_sum = cash_sum_
    cashless_count = cashless_count_
    cashless_sum = cashless_sum_
    today = datetime.today
    if cash_sum_ is None:
        cash_sum_ = 0
    if cashless_sum_ is None:
        cashless_sum_ = 0
    total_sum = int(cash_sum_) + int(cashless_sum_)
    filters = PaymentLogFilters(request.POST, queryset=PaymentLog.objects.all())
    paginator = Paginator(filters.qs, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'cash_count': cash_count,
        'cash_sum': cash_sum,
        'cashless_count': cashless_count,
        'cashless_sum': cashless_sum,
        'total_sum': total_sum,
        'today': today,
        'filters': filters,
        'outlay_sum': outlay_sum,
    }
    return render(request, 'paymentlog.html', context)


class PaymentLogDeleteView(DeleteView):
    model = PaymentLog
    success_url = reverse_lazy('payment_log:list')

paymentlog/templates/paymentlog.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block css %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock %}



{% block body %}
<main class="container">
  <div class="row">
    <div class="col-md-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'sauna:calendar_view' %}">Главная</a></li>
              <li class="breadcrumb-item active" aria-current="page">Все приходы</li>
            </ol>
          </nav>
    </div>
    <div class="col-md-8 border-bottom">
        <h1 class="h3">Приход за день {{ today.date }}</h1>
    </div>
  </div>
  <div class="row">
  <div class="col-md-12">
    <table class="table table-bordered">
        <tr>
            <td class="table-secondary">Наличный расчет: ({{ cash_count }}) </td>
            {% if cash_sum is None %}
                <td class="cash_sum">0 Сум</td>
                {% else %}
                    <td class="cash_sum">{{ cash_sum|intcomma }} Сум</td>
            {% endif %}

        <td class="table-secondary">Безналичный расчет: ({{ cashless_count }}) </td>
            {% if cashless_sum is None %}
                <td class="cashless_sum">0 Сум</td>
                {% else %}
                    <td class="cashless_sum">{{ cashless_sum|intcomma }} Сум</td>
            {% endif %}
        <td class="table-secondary">Итого</td>
        <td><span style="font-weight: bold;">{{ total_sum|intcomma }} Сум</span></td>
        </tr>
        <tr>
            <td class="table-secondary" colspan="5">Сумма расходов на сегодня</td>
            {% if outlay_sum is None %}
                <td class="cash_sum" style="font-weight: bold;">0 Сум</td>
                {% else %}
                    <td class="cash_sum" style="font-weight: bold;">{{ outlay_sum|intcomma }} Сум</td>
            {% endif %}
        </tr>
        <tr>
            <td class="table-secondary" colspan="5">Чистый доход на сегодня</td>
            <td class="show_original_income" style="font-weight: bold;"></td>
        </tr>
    </table>
</div>
    <div class="col-md-12 border-bottom">
        <h1 class="h3">Все приходы</h1>
    </div>
  <div class="d-flex justify-content-end my-3">
      <form class="d-flex justify-content-end" action="{% url 'payment_log:list' %}" method="POST">
          {% csrf_token %}
          <div class="col-md-3 mx-1">
                    {{ filters.form.created|as_crispy_field }}
{#                <input name="created_date" type="text" id="datepicker" class="form-control form-control-sm" placeholder="Дата создания">#}
          </div>
          <div class="col-md-3 mx-1">
{#                <label for="select_type">Тип оплаты</label>#}
{#            <select id="select_type" name="payment_type" class="form-select form-select-sm">#}
{#                <option disabled selected value="">Тип оплаты</option>#}
{#                <option value="advance">Аванс</option>#}
{#                <option value="payment">Оплата</option>#}
{#            </select>#}
              {{ filters.form.payment_type|as_crispy_field }}
        </div>
          <div class="col-md-3 mx-1">
{#                <label for="select_type">Метод оплаты</label>#}
{#            <select id="select_type" name="payment_method" class="form-select form-select-sm">#}
{#                <option disabled selected value="">Метод оплаты</option>#}
{#                <option value="cash">Наличный</option>#}
{#                <option value="cashless">Безналичный расчет</option>#}
{#            </select>#}
          {{ filters.form.payment_method|as_crispy_field }}
        </div>
          <div class="col-md-1">
              <div class="mx-2">
                  <label>Поиск</label>
                <button type="submit" class="btn btn-sm btn-secondary">
                    <img alt="/" src="{% static 'images/search-solid.svg' %}" class="img-fluid" style="width: 35px; height: 20px;">
                </button>
            </div>
          </div>
      </form>
  </div>
    <div class="col-md-12">
          <table class="table table-bordered table-striped table-sm text-center">
              <thead class="table-dark ">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Заказ</th>
                    <th scope="col">Созданный</th>
                    <th scope="col">Скидка</th>
                    <th scope="col">Сумма после скидки</th>
                    <th scope="col">Тип оплаты</th>
                    <th scope="col">Метод оплаты</th>
                    <th scope="col">Комментарий</th>
                    <th scope="col"></th>
                </tr>
              </thead>
               <tbody>
               {% for i in page_obj %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>
                        <a href="{% url 'order:each' i.order.id %}" class="btn btn-sm btn-info">
                            Заказ N {{ i.order }}
                        </a>
                    </td>
                    <td>{{ i.created.date }}</td>
                    <td>{{ i.discount|default:"0" }}</td>
                    <td>{{ i.amount|intcomma }}</td>
                    <td>{{ i.get_payment_type_display }}</td>
                    <td>{{ i.get_payment_method_display }}</td>
                    <td>{{ i.comment }}</td>
                    <td>
                        <div class="d-grid gap-2 d-md-block">
                            <form type="hidden" method="POST" action="{% url 'payment_log:delete' i.pk %}">
                                {% csrf_token %}
                                <input type="hidden" value="DELETE">
                                <button class="btn btn-danger btn-sm" type="submit">Удалить</button>
                            </form>
                        </div>
                    </td>
                  </tr>
                   {% empty %}
                   <tr>
                       <td colspan="9">Пусто</td>
                   </tr>
               {% endfor %}
                </tbody>
               <tfoot class="table-success fw-bolder">
                <tr>
                  <th scope="row"></th>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td class="payment_total_show"></td>
                  <td></td>
                    <td></td>
                    <td></td>
                  <td></td>
                </tr>
              </tfoot>
          </table>
    <div aria-label="Page navigation example">
        <span class="pagination">
            {% if page_obj.has_previous %}
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo; предыдущий</a>
            {% endif %}

            <span class="current page-link">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">следующий &raquo;</a>
            {% endif %}
        </span>
    </div>
    </div>
  </div>
</main>
{% endblock %}


{% block js %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>

        $( "#datepicker" ).datepicker({
            dateFormat: 'yy-mm-dd',
        });

        let payment_total_show = 0
        {% for i in page_obj %}
            payment_total_show += {{ i.amount }}
        {% endfor %}
        $('.payment_total_show').html(payment_total_show.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " "))

        let method_count = parseInt($('.cashless_count').html()) + parseInt($('.cash_count').html());
        $('.method_count').html(method_count.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " "))

        let show_original_income = 0
        show_original_income = {{ total_sum|default:0 }} - {{ outlay_sum|default:0 }};
        $('.show_original_income').html(show_original_income.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ") + ' Сум')
    </script>
{% endblock %}