client/urls.py
from django.urls import path
from .views import ClientAddView, ClientView, ClientEditView, ClientDeleteView, ClientHistoryView, client_order_item_ajax
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('', login_required(ClientView.as_view()), name='list'),
    path('add/', login_required(ClientAddView.as_view()), name='add'),
    path('edit/<int:pk>', login_required(ClientEditView.as_view()), name='edit'),
    path('delete/<int:pk>', login_required(ClientDeleteView.as_view()), name='delete'),
    path('history/<int:pk>', login_required(ClientHistoryView.as_view()), name='history'),
    path('order-item/', login_required(client_order_item_ajax), name='order_item'),
]

order/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import OrderEachView, OrderProductAddView, OrderItemDeleteView, OrderCloseView, OrderDeleteView, \
    OrderEditView, OrderPaymentCreate, OrderPaymentDeleteView, OrderList, OrderPenaltyAdd, OrderPenaltyDelete


urlpatterns = [
    path('each/<int:pk>', login_required(OrderEachView.as_view()), name='each'),
    path('list/', login_required(OrderList.as_view()), name='list'),
    path('penalty_delete/<int:pk>', login_required(OrderPenaltyDelete.as_view()), name='penalty-delete'),
    path('penalty_add/<int:pk>', login_required(OrderPenaltyAdd.as_view()), name='penalty-add'),
    path('product-add/', login_required(OrderProductAddView.as_view()), name='product-add'),
    path('product-delete/<int:pk>', login_required(OrderItemDeleteView.as_view()), name='product-delete'),
    path('close/<int:pk>', login_required(OrderCloseView.as_view()), name='close'),
    path('delete/<int:pk>', login_required(OrderDeleteView.as_view()), name='delete'),
    path('edit/<int:pk>', login_required(OrderEditView.as_view()), name='edit'),
    path('payment-create/', login_required(OrderPaymentCreate.as_view()), name='payment-create'),
    path('payment-delete/<int:pk>', login_required(OrderPaymentDeleteView.as_view()), name='payment-delete'),
]

system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('sauna.urls', 'sauna'), namespace='sauna')),
    path('client/', include(('client.urls', 'client'), namespace='client')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('payment-log/', include(('paymentlog.urls', 'paymentlog'), namespace='payment_log')),
    path('outlay/', include(('outlay.urls', 'outlay'), namespace='outlay')),
]

client/models.py
from django.db import models
from .choices import CLIENT_STATUS, CLIENT_TYPE


class Client(models.Model):
    name = models.CharField(max_length=500, verbose_name='Имя')
    phone = models.CharField(max_length=500, unique=True, verbose_name='Телефон')
    client_type = models.CharField(max_length=500, choices=CLIENT_TYPE, default='normal', verbose_name='Тип клиента')
    status = models.CharField(max_length=500, choices=CLIENT_STATUS, default='active', verbose_name='Статус')
    content = models.CharField(max_length=700, blank=True, null=True, verbose_name='Содержание')

    def __str__(self):
        return f"{self.name} / {self.get_client_type_display()}"

client/forms.py
from django import forms
from .models import Client


class ClientAddForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

client/views.py
from django.shortcuts import reverse
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.core import serializers
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Client
from product.models import Product
from order.models import Order, OrderItem
from .forms import ClientAddForm
import json


class ClientAddView(CreateView):
    model = Client
    template_name = 'client_add.html'
    form_class = ClientAddForm

    def get_success_url(self):
        return reverse('client:list')


class ClientView(ListView):
    model = Client
    paginate_by = 10
    template_name = 'clients_list.html'


class ClientEditView(UpdateView):
    model = Client
    template_name = 'client_edit.html'
    form_class = ClientAddForm

    def get_success_url(self):
        return reverse('client:list')


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('client:list')


class ClientHistoryView(DetailView):
    model = Client
    template_name = 'client_history.html'
    context_object_name = 'client'

    def get_context_data(self, **kwargs):
        context = super(ClientHistoryView, self).get_context_data()
        context['order'] = Order.objects.filter(client_id=self.kwargs['pk'])
        return context


def client_order_item_ajax(request):
    data = json.loads(request.body)
    query = OrderItem.objects.filter(order_id=int(data['pk']))
    product = Product.objects.all()
    all_obj = [*query, *product]
    order_item = serializers.serialize('json', all_obj)
    return HttpResponse(order_item)

client/templates/client_add.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
{% endblock %}


{% block body %}
    <div class="container">
        <div class="card p-4">
            <h3 class="my-3">Добавить клиента</h3>
            <form method="POST" action="#">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        {{ form.name|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.phone|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.client_type|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.status|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.content|as_crispy_field }}
                    </div>
                </div>
{#                {{ form|crispy }}#}
                <button type="submit" class="btn btn-success my-4">Добавить</button>
                <a href="{% url 'client:list' %}" class="btn btn-secondary">Назад</a>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}

{% endblock %}

client/templates/client_edit.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
{% endblock %}


{% block body %}
    <div class="container">
        <div class="card p-4">
            <h3 class="my-3">Изменить клиента</h3>
            <form method="POST" action="#">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        {{ form.name|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.phone|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.client_type|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.status|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.content|as_crispy_field }}
                    </div>
                </div>
                <button type="submit" class="btn btn-success my-4">Изменить</button>
                <a href="{% url 'client:list' %}" class="btn btn-secondary">Назад</a>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}

{% endblock %}

client/templates/client_history.html
{% extends 'layout.html' %}
{% load static %}
{% load humanize %}

{% block css %}
{% endblock %}


{% block body %}
<main class="container">
  <div class="row">
    <div class="col-md-6 border-bottom">
        <h1 class="h3">
            История клиента
        </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
         <h2 class="h5 my-3">{{ client.name }} / {{ client.phone }}</h2>
          <table class="table table-bordered table-striped table-sm text-center">
              <thead class="table-dark ">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Сауна</th>
                    <th scope="col">Дата</th>
                  <th scope="col">Кол людей</th>
                  <th scope="col">Сумма за 1 час</th>
                  <th scope="col">Часы</th>
                    <th scope="col">-</th>
                </tr>
              </thead>
               <tbody>
               {% for i in order %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ i.sauna }}</td>
                    <td>{{ i.start_time }}</td>
                    <td>{{ i.people_count }}</td>
                    <td>{{ i.sauna_hour_price|intcomma }}</td>
                    <td>{{ i.hours }}</td>
                      <td>
                          <button class="btn btn-info more_btn" data-pk="{{ i.pk }}" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            еще
                          </button>
                      </td>
                  </tr>
                   {% empty %}
                   <tr>
                    <td colspan="8">Empty</td>
                   </tr>
               {% endfor %}

                </tbody>
                <tfoot class="table-warning fw-bolder">
                  <tr>
                    <th colspan="8">
                        &nbsp
                    </th>
                  </tr>
                </tfoot>
          </table>
    </div>
  </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-xl">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Дополнительное</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                      <div class="row">
                      <div class="col-md-12">
                            <!-- what we got -->
                              <h2 class="h5">Таблица заказов</h2>
                              <div class="border border-success p-2">
                                          <table class="table table-bordered table-striped table-sm text-center">
                                              <thead class="table-dark ">
                                                <tr>
                                                  <th scope="col">#</th>
                                                  <th scope="col">Наименование</th>
                                                  <th scope="col">Кол</th>
                                                  <th scope="col">Един</th>
                                                  <th scope="col">Общая</th>
                                                </tr>
                                              </thead>
                                              <tbody class="product_show_table">

                                              </tbody>
                                              <tfoot class="table-success fw-bolder">
                                                <tr>
                                                  <th scope="row"></th>
                                                  <td></td>
                                                  <td></td>
                                                  <td></td>
                                                  <td class="product_show_table_total">0</td>
                                                </tr>
                                              </tfoot>
                                            </table>
                              </div>
                            <!-- what we got -->
                      </div>
                  </div>
                  </div>
                </div>
              </div>
            </div>

</main>
{% endblock %}


{% block js %}
    <script>
        $('.more_btn').on('click', function(){
            $('.product_show_table').html('');
            $.ajax({
                url: "{% url 'client:order_item' %}",
                type: 'POST',
                headers: {
                    'X-CSRFToken': csrftoken
                },
                data: JSON.stringify({
                    'pk': $(this).attr('data-pk'),
                }),
                contentType: 'application/json',
                dataType: 'json',
                success: function(e) {
                    console.log(e)
                    let counter = 0
                    for(let i=0; i < e.length; i++) {
                        if(e[i]['model'] === 'order.orderitem') {
                            counter += e[i]['fields']['total']
                            for(let j=0; j < e.length; j++){
                                if(e[j]['model'] === 'product.product') {
                                    if(e[i]["fields"]["product"] === e[j]['pk']) {
                                        let price = e[i]["fields"]["price"].toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ")
                                        let total = e[i]["fields"]["total"].toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ")
                                        $('.product_show_table').append(
                                            '<tr>' +
                                                '<th scope="row">#</th>' +
                                                '<td>' + e[j]["fields"]["title"] + '</td>' +
                                                '<td>' + e[i]["fields"]["count"] + '</td>' +
                                                '<td>' + price + '</td>' +
                                                '<td>' + total + '</td>' +
                                            '</tr>'
                                        )
                                    }
                                }
                            }
                        }
                    }
                    $('.product_show_table_total').html(counter.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " "))
                },
                error: function(error) {
                    console.log(error)
                }
            })
        });
    </script>
{% endblock %}

client/templates/clients_list.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
{% endblock %}



{% block body %}
<main class="container">
  <div class="row">
    <div class="col-md-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Главная</a></li>
              <li class="breadcrumb-item active" aria-current="page">Все клиенты</li>
            </ol>
          </nav>
    </div>
    <div class="col-md-8 border-bottom">
        <h1 class="h3">Клиенты</h1>
    </div>
    <div class="col-md-4 border-bottom">
      <a href="{% url 'client:add' %}" class="btn btn-success">
          Добавить клиента
      </a>
    </div>
  </div>
  <div class="row">

    <div class="col-md-12">
          <table class="table table-bordered table-striped table-sm text-center">
              <thead class="table-dark ">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Тип клиента</th>
                  <th scope="col">Имя</th>
                  <th scope="col">Контакты</th>
                  <th scope="col">Статус</th>
                  <th scope="col">Примечание</th>
                  <th scope="col"></th>
                </tr>
              </thead>
               <tbody>
               {% for i in page_obj %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ i.get_client_type_display }}</td>
                    <td>{{ i.name }}</td>
                    <td>{{ i.phone }}</td>
                    <td>{{ i.get_status_display }}</td>
                    <td>{{ i.content|default:'' }}</td>
                    <td> 
                        <div class="d-grid gap-2 d-md-block">
                          <a href="{% url 'client:history' i.pk %}" class="btn btn-info btn-sm" type="button">История</a>
                          <a href="{% url 'client:edit' i.pk %}" class="btn btn-primary btn-sm" type="button">Редактировать</a>
                          <button id="btn{{ i.pk }}" class="btn btn-danger btn-sm" type="submit">Удалить</button>
                            <form id="form{{ i.pk }}" type="hidden" method="POST" action="{% url 'client:delete' i.pk %}">
                                {% csrf_token %}
                            </form>
                        </div>
                    </td>
                  </tr>
                   {% empty %}
                   <tr>
                       <td colspan="7">Empty</td>
                   </tr>
               {% endfor %}
                </tbody>
          </table>
    <div aria-label="Page navigation example">
        <span class="pagination">
            {% if page_obj.has_previous %}
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo; предыдущий</a>
            {% endif %}

            <span class="current page-link">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">следующий &raquo;</a>
            {% endif %}
        </span>
    </div>
    </div>
  </div>
</main>
{% endblock %}


{% block js %}
    <script>
        {% for i in object_list %}
            $('#btn{{ i.pk }}').on('click', function(){
               $('#form{{ i.pk }}').submit();
            });
        {% endfor %}


    </script>
{% endblock %}