order/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import OrderEachView, OrderProductAddView, OrderItemDeleteView, OrderCloseView, OrderDeleteView, \
    OrderEditView, OrderPaymentCreate, OrderPaymentDeleteView, OrderList, OrderPenaltyAdd, OrderPenaltyDelete


urlpatterns = [
    path('each/<int:pk>', login_required(OrderEachView.as_view()), name='each'),
    path('list/', login_required(OrderList.as_view()), name='list'),
    path('penalty_delete/<int:pk>', login_required(OrderPenaltyDelete.as_view()), name='penalty-delete'),
    path('penalty_add/<int:pk>', login_required(OrderPenaltyAdd.as_view()), name='penalty-add'),
    path('product-add/', login_required(OrderProductAddView.as_view()), name='product-add'),
    path('product-delete/<int:pk>', login_required(OrderItemDeleteView.as_view()), name='product-delete'),
    path('close/<int:pk>', login_required(OrderCloseView.as_view()), name='close'),
    path('delete/<int:pk>', login_required(OrderDeleteView.as_view()), name='delete'),
    path('edit/<int:pk>', login_required(OrderEditView.as_view()), name='edit'),
    path('payment-create/', login_required(OrderPaymentCreate.as_view()), name='payment-create'),
    path('payment-delete/<int:pk>', login_required(OrderPaymentDeleteView.as_view()), name='payment-delete'),
]

outlay/urls.py
from django.urls import path
from .views import OutlayListView, OutlayCategoryCreateView, OutlayDeleteView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('list/', login_required(OutlayListView.as_view()), name='list'),
    path('category-add/', login_required(OutlayCategoryCreateView.as_view()), name='category-add'),
    path('category-delete/<int:pk>', login_required(OutlayDeleteView.as_view()), name='category-delete'),
]

system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('sauna.urls', 'sauna'), namespace='sauna')),
    path('client/', include(('client.urls', 'client'), namespace='client')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('payment-log/', include(('paymentlog.urls', 'paymentlog'), namespace='payment_log')),
    path('outlay/', include(('outlay.urls', 'outlay'), namespace='outlay')),
]

outlay/models.py
from django.db import models
from datetime import datetime


class OutlayCategory(models.Model):
    name = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class Outlay(models.Model):
    category = models.ForeignKey(OutlayCategory, on_delete=models.CASCADE, verbose_name='Категория')
    name = models.CharField(max_length=500, verbose_name='Причина')
    summa = models.IntegerField(verbose_name='Сумма')
    created = models.DateTimeField(default=datetime.today().strftime('%Y-%m-%d'))

    def __str__(self):
        return self.name

outlay/views.py
from django.views.generic.edit import CreateView, DeleteView
from .models import Outlay, OutlayCategory
from paymentlog.models import PaymentLog
from django.urls import reverse_lazy
from datetime import datetime
from django.db.models import Sum
from datetime import date


class OutlayListView(CreateView):
    model = Outlay
    fields = ('category', 'name', 'summa')
    success_url = reverse_lazy('outlay:list')
    template_name = 'outlay.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        outlay_for_today = Outlay.objects.filter(created=datetime.today().strftime('%Y-%m-%d'))
        outlay_count = outlay_for_today.count()
        outlay_sum = outlay_for_today.aggregate(sum=Sum('summa'))['sum']
        context['outlay_count'] = outlay_count
        context['outlay_sum'] = outlay_sum
        context['outlay'] = Outlay.objects.all()
        context['day'] = datetime.now()
        cash = PaymentLog.objects.filter(created=date.today().today())
        cash_sum = cash.aggregate(sum=Sum('amount'))['sum']
        context['money_for_today'] = cash_sum
        return context

    def form_valid(self, form):

        return super().form_valid(form)


class OutlayCategoryCreateView(CreateView):
    model = OutlayCategory
    fields = ('name', )
    success_url = reverse_lazy('outlay:list')


class OutlayDeleteView(DeleteView):
    model = Outlay
    success_url = reverse_lazy('outlay:list')

outlay/templates/outlay.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block css %}
{% endblock %}



{% block body %}
<main class="container">
  <div class="row">
    <div class="col-md-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Главная</a></li>
              <li class="breadcrumb-item active" aria-current="page">Все расходы</li>
            </ol>
          </nav>
    </div>
    <div class="col-md-8 border-bottom">
        <h1 class="h3">Расход за день {{ day.date }}</h1>
    </div>
      <div class="col-md-2 border-bottom">
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#example1Modal">
              Добавить категория
          </button>
    </div>
    <div class="col-md-2 border-bottom">
      <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Добавить расход
      </button>
    </div>
  </div>
  <div class="row">
  <div class="col-md-12">
    <table class="table table-bordered">
        <tr>
            <td class="table-secondary">Количество расходов: ({{ outlay_count }})</td>
            {% if outlay_sum is None %}
                <td class="cash_sum">0 Сум</td>
                {% else %}
                    <td class="cash_sum">{{ outlay_sum|intcomma }} Сум</td>
            {% endif %}
        <td class="table-secondary">Итого</td>
        {% if outlay_sum is None %}
                <td class="cash_sum" style="font-weight: bold;">0 Сум</td>
                {% else %}
                    <td class="cash_sum" style="font-weight: bold;">{{ outlay_sum|intcomma }} Сум</td>
            {% endif %}
        </tr>
    </table>
</div>
    <div class="col-md-12">
          <table class="table table-bordered table-striped table-sm text-center">
              <thead class="table-dark ">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Категория</th>
                    <th scope="col">Причина</th>
                    <th scope="col">Сумма</th>
                    <th scope="col">Созданный</th>
                    <th scope="col"></th>
                </tr>
              </thead>
               <tbody>
               {% for i in outlay %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ i.category }}</td>
                    <td>{{ i.name }}</td>
                    <td>{{ i.summa|intcomma }}</td>
                      <td>{{ i.created }}</td>
                    <td>
                        <div class="d-grid gap-2 d-md-block">
                            <form type="hidden" method="POST" action="{% url 'outlay:category-delete' i.pk %}">
                                {% csrf_token %}
                                <input type="hidden" value="DELETE">
                                <button class="btn btn-danger btn-sm" type="submit">Удалить</button>
                            </form>
                        </div>
                    </td>
                  </tr>
                   {% empty %}
                   <tr>
                       <td colspan="6">Пусто</td>
                   </tr>
               {% endfor %}
                </tbody>
               <tfoot class="table-success fw-bolder">
                <tr>
                  <th scope="row"></th>
                  <td></td>
                  <td></td>
                  <td class="outlay_total_show"></td>
                  <td></td>
                    <td></td>
                </tr>
              </tfoot>
          </table>
    </div>
  </div>
</main>

    <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Новый расход</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <form class="row g-3" method="POST" action="">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <p class="text-secondary show_total_cash">В кассе есть {{ money_for_today|intcomma }} сум</p>
                        <button class="btn btn-primary">Добавить</button>
                      </form>
                  </div>
                </div>
              </div>
            </div>

   <div class="modal fade" id="example1Modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Новая категория</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              <form class="row g-3" method="POST" action="{% url 'outlay:category-add' %}">
                {% csrf_token %}
                <label for="for_cat_name">Имя категории</label>
                <input id="for_cat_name" class="form-control" name="name" required>
                <button class="btn btn-success" type="submit">Добавить</button>
              </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}


{% block js %}
    <script>
    let outlay_total_show = 0
    {% for i in outlay %}
        outlay_total_show += {{ i.summa }}
    {% endfor %}
    $('.outlay_total_show').html(outlay_total_show.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " "))

    let show_total_cash = 0
    show_total_cash = {{ money_for_today|default:0 }} - {{ outlay_sum|default:0  }};
    $('.show_total_cash').html('В кассе есть ' + show_total_cash.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ") +' сум')
    </script>
{% endblock %}