client/urls.py
from django.urls import path
from .views import ClientAddView, ClientView, ClientEditView, ClientDeleteView, ClientHistoryView, client_order_item_ajax
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('', login_required(ClientView.as_view()), name='list'),
    path('add/', login_required(ClientAddView.as_view()), name='add'),
    path('edit/<int:pk>', login_required(ClientEditView.as_view()), name='edit'),
    path('delete/<int:pk>', login_required(ClientDeleteView.as_view()), name='delete'),
    path('history/<int:pk>', login_required(ClientHistoryView.as_view()), name='history'),
    path('order-item/', login_required(client_order_item_ajax), name='order_item'),
]

order/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import OrderEachView, OrderProductAddView, OrderItemDeleteView, OrderCloseView, OrderDeleteView, \
    OrderEditView, OrderPaymentCreate, OrderPaymentDeleteView, OrderList, OrderPenaltyAdd, OrderPenaltyDelete


urlpatterns = [
    path('each/<int:pk>', login_required(OrderEachView.as_view()), name='each'),
    path('list/', login_required(OrderList.as_view()), name='list'),
    path('penalty_delete/<int:pk>', login_required(OrderPenaltyDelete.as_view()), name='penalty-delete'),
    path('penalty_add/<int:pk>', login_required(OrderPenaltyAdd.as_view()), name='penalty-add'),
    path('product-add/', login_required(OrderProductAddView.as_view()), name='product-add'),
    path('product-delete/<int:pk>', login_required(OrderItemDeleteView.as_view()), name='product-delete'),
    path('close/<int:pk>', login_required(OrderCloseView.as_view()), name='close'),
    path('delete/<int:pk>', login_required(OrderDeleteView.as_view()), name='delete'),
    path('edit/<int:pk>', login_required(OrderEditView.as_view()), name='edit'),
    path('payment-create/', login_required(OrderPaymentCreate.as_view()), name='payment-create'),
    path('payment-delete/<int:pk>', login_required(OrderPaymentDeleteView.as_view()), name='payment-delete'),
]

sauna/urls.py
from django.urls import path
from .views import CalendarView, LoginView, LogoutView, OrderAddView, get_sauna_type_ajax, ChangePassword
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', login_required(LogoutView.as_view()), name='logout'),
    path('pass_change/<int:pk>', login_required(ChangePassword.as_view()), name='password_change'),
    path('sauna/', login_required(CalendarView.as_view()), name='calendar_view'),
    path('order/add/', login_required(OrderAddView.as_view()), name='order-add'),
    path('sauna_type_ajax/', login_required(get_sauna_type_ajax), name='get_sauna_type_ajax'),
]

system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('sauna.urls', 'sauna'), namespace='sauna')),
    path('client/', include(('client.urls', 'client'), namespace='client')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('payment-log/', include(('paymentlog.urls', 'paymentlog'), namespace='payment_log')),
    path('outlay/', include(('outlay.urls', 'outlay'), namespace='outlay')),
]

sauna/models.py
from django.db import models
from .choices import SAUNA_STATUS, COLOR


class Sauna(models.Model):
    name = models.CharField(max_length=500, verbose_name='Сауна')
    status = models.CharField(max_length=500, choices=SAUNA_STATUS, default='active', verbose_name='Сауна статус')
    color = models.CharField(max_length=200, choices=COLOR, default='yellow', verbose_name='Цвет')

    class Meta:
        verbose_name = 'Сауна'
        verbose_name_plural = 'Сауна'

    def __str__(self):
        return self.name


class SaunaPriceTypes(models.Model):
    sauna = models.ForeignKey(Sauna, on_delete=models.CASCADE, verbose_name='Сауна')
    min_people = models.IntegerField(verbose_name='Мин. человек')
    max_people = models.IntegerField(verbose_name='Макс. человек')
    price = models.IntegerField(verbose_name='Цена')

    class Meta:
        verbose_name = 'Сауна цена'
        verbose_name_plural = 'Сауна цена'

    def __str__(self):
        return self.sauna.name

sauna/forms.py
from django import forms
from order.models import Order


class OrderAddForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('client', 'sauna', 'people_count', 'hours', 'start_time', 'end_time')

sauna/views.py
from order.models import Order
from client.models import Client
from client.forms import ClientAddForm
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from .forms import OrderAddForm
from .helper import count_sauna_price
from django.views.generic import View
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from sauna.models import Sauna, SaunaPriceTypes
from django.core import serializers
from django.http import HttpResponse
from django.contrib.auth.models import User
import json


class LoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('sauna:calendar_view')
        return render(request, 'signin.html')

    def post(self, request):
        user = authenticate(username=str(request.POST.get('login')), password=str(request.POST.get('password')))
        if user is not None:
            login(request, user)
            return redirect('sauna:calendar_view')
        return render(request, 'signin.html')


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('sauna:login')


class CalendarView(ListView):
    model = Order
    template_name = 'index.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderAddForm
        context['order'] = Order.objects.all()
        context['clients'] = Client.objects.all()
        context['client_form'] = ClientAddForm
        context['sauna'] = Sauna.objects.all()
        return context


class OrderAddView(CreateView):
    model = Order
    fields = ['hours']
    success_url = reverse_lazy('sauna:calendar_view')

    def form_valid(self, form):
        action = 'add'
        count_sauna_price(self, form, action)
        return super().form_valid(form)


def get_sauna_type_ajax(request):
    data = json.loads(request.body)
    queryset = SaunaPriceTypes.objects.filter(sauna_id=int(data['sauna_id']))
    context = serializers.serialize('json', queryset)
    return HttpResponse(context)


class ChangePassword(UpdateView):
    model = User
    fields = ['username', 'first_name', 'password']
    template_name = 'change_password.html'
    success_url = reverse_lazy('sauna:calendar_view')

    def form_valid(self, form):
        if self.request.POST.get('use_current_password'):
            form.instance.username = str(self.request.POST.get('username'))
            form.instamce.first_name = str(self.request.POST.get('first_name'))
            current_password = User.objects.get(id=int(self.kwargs['pk']))
            form.instance.password = current_password
        return form

    def form_invalid(self, form):
        print('lala')
        return HttpResponse(form.errors)

sauna/templates/change_password.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
{% endblock %}


{% block body %}
    <div class="container">
        <div class="card p-4">
            <h3 class="my-3">Сменить пароль для</h3>
            <form method="POST" name="password_form">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-4">
                        <label for="login">Логин</label>
                        <input id="login" class="form-control" type="text" required name="username">
{#                        <a type="button" class="bg-light" id="show_password">#}
{#                            <img style="width: 15px; height: 15px;" class="img-fluid" alt="/" src="{% static 'images/eye_icon.png' %}">#}
{#                        </a>#}
                    </div>
                    <div class="col-md-4">
                        <label for="first_name">Имя</label>
                        <input id="first_name" class="form-control" type="text" required name="first_name">
                    </div>
                    <div class="col-md-4">
                        <label for="use_current_password">Не изменит пароль</label>
                        <input id="use_current_password" type="checkbox" class="form-check" name="use_current_password">
                    </div>
                    <div class="col-md-4">
                        <label for="password">Текущий пароль</label>
                        <input id="password" class="form-control" type="password" required>
                        <a type="button" class="bg-light" id="show_password">
                            <img style="width: 15px; height: 15px;" class="img-fluid" alt="/" src="{% static 'images/eye_icon.png' %}">
                        </a>
                    </div>
                    <div class="col-md-4">
                        <label for="password_new">Новый пароль</label>
                        <input id="password_new" class="form-control" type="password" name="password" required>
                        <a href="#" class="bg-light" id="show_password_new">
                            <img style="width: 15px; height: 15px;" class="img-fluid" alt="/" src="{% static 'images/eye_icon.png' %}">
                        </a>
                    </div>
                    <div class="col-md-4">
                        <label for="password_new_repeat">Повтор нового пароля</label>
                        <input id="password_new_repeat" class="form-control" type="password" required>
                        <p class="text-danger d-none password_new_repeat_check">Пароль не совпадает</p>
                        <a href="#" class="bg-light" id="show_password_new_repeat">
                            <img style="width: 15px; height: 15px;" class="img-fluid" alt="/" src="{% static 'images/eye_icon.png' %}">
                        </a>
                    </div>
                </div>
                <button type="button" class="btn btn-success my-4 form_btn">Изменить</button>
                {{ request.user.password }}
                <a href="{% url 'sauna:calendar_view' %}" class="btn btn-secondary">Назад</a>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function(){
            $('#show_password').on('click', function(){
                if('password' === $('#password').attr('type')) {
                    $('#password').attr('type', 'text')
                } else {
                    $('#password').attr('type', 'password')
                }
            })
            $('#show_password_new').on('click', function(){
                if('password' === $('#password_new').attr('type')) {
                    $('#password_new').attr('type', 'text')
                } else {
                    $('#password_new').attr('type', 'password')
                }
            })
            $('#show_password_new_repeat').on('click', function(){
                if('password' === $('#password_new_repeat').attr('type')) {
                    $('#password_new_repeat').attr('type', 'text')
                } else {
                    $('#password_new_repeat').attr('type', 'password')
                }
            })
            let checker = 0
            $('.form_btn').on('click', function(){
                if(checker === 0) {
                    $('.password_new_repeat_check').addClass('d-none')
                    if($('#password_new').val() === $('#password_new_repeat').val() && $('#password_new_repeat').val() !== '') {
                        password_form.submit()
                    } else {
                        $('.password_new_repeat_check').removeClass('d-none')
                    }
                } else {
                    input = '<input type="number" name="password" value="{{ request.user.password }}">'
                    $(input).appendTo($('form[name="password_form"]'))
                    password_form.submit()
                }
            })

            $('#use_current_password').on('click', function(){
                if(checker === 0) {
                    $('#password').prop('disabled', true)
                    $('#password_new').prop('disabled', true)
                    $('#password_new_repeat').prop('disabled', true)
                    checker = 1;
                } else {
                    $('#password').prop('disabled', false)
                    $('#password_new').prop('disabled', false)
                    $('#password_new_repeat').prop('disabled', false)
                    checker = 0;
                }
            })
        })
    </script>
{% endblock %}

sauna/templates/index.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <style>
        #calendar {
        width: 100%;
        }
    </style>
{% endblock %}


{% block body %}
    <!--MAIN BODY-->
    <main class="container">
      <div class="row align-items-center">
        <div class="col-md-12">
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url 'sauna:calendar_view' %}">Главная</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Календарь бронирование</li>
                </ol>
              </nav>
        </div>
        <div class="col-md-6">
            <h1 class="h3">Календарь бронирование</h1>
        </div>
          <div class="col-md-4">
{#              <label for="select_2">Поиск клиента</label>#}
                <select id="select_2" onchange="location= this.value" class="js-example-basic-single js-states form-control" name="client">
                <option value="" disabled selected>Поиск существующих клиентов</option>
                {% for i in clients %}
                        <option value="{% url 'client:history' i.pk %}">{{ i.name }} / {{ i.phone }}</option>
                {% endfor %}
            </select>
          </div>
      <div class="col-md-2 text-end">
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Новый брон
            </button>
      </div>
        <div class="col-md-2 ml-auto">
           <!--modal-->
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-xl">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Новое бронирование</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <form class="row g-3" method="POST" action="{% url 'sauna:order-add' %}">
                        {% csrf_token %}
                        <div class="col-md-6">
                            <label for="select_3" class="mb-3">Клиенты</label><br>
                            <select id="select_3" style="width: 100%" class="js-example-basic-single js-states form-control" name="client_id">
                                {% for i in clients %}
                                        <option value="{{ i.pk }}">{{ i.name }} / {{ i.phone }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-6">
                          <label for="sauna_select" class="form-label">Сауна</label>
{#                            {{ form.sauna|as_crispy_field }}#}
                            <select name="sauna" class="form-select" id="sauna_select" required>
                                <option value="" disabled selected>---</option>
                                {% for i in sauna %}
                                    <option value="{{ i.id }}">{{ i.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-3">
                          <label for="inputAddress" class="form-label m-0">Количество человека</label>
{#                            {{ form.people_count|as_crispy_field }}#}
                          <input type="number" min="1" name="people_count" class="form-control people_count" id="inputAddress" required>
                        </div>
                        <div class="col-md-3">
{#                          <label for="inputAddress2" class="form-label">Длительность</label>#}
                            {{ form.hours|as_crispy_field }}
{#                          <input type="number" name="hours" class="form-control" id="inputAddress2" min="0">#}
                        </div>
                        <div class="col-md-3">
{#                          <label for="inputCity" class="form-label">Начало</label>#}
{#                            {{ form.start_time|as_crispy_field }}#}
                            <p>Начало бронирования: <input name="start" type="text" id="datepicker" class="form-control start_time_input" required></p>
{#                          <input type="text" class="form-control" id="inputCity">#}
                        </div>
                        <div class="col-md-3">
{#                          <label for="inputState" class="form-label">Конец</label>#}
{#                            {{ form.end_time|as_crispy_field }}#}
                            <p>Конец бронирования: <input name="end" type="text" id="datepicker1" class="form-control end_time_input" required></p>
{#                          <select id="inputState" class="form-select">#}
{#                            <option selected>Choose...</option>#}
{#                            <option>...</option>#}
{#                          </select>#}
                        </div>
                        <div class="col-12">
                            <div class="show_sauna_price_info d-none">
                                <p>Сумма сауны за час <b><span class="show_sum_for_sauna"></span></b> от <b><span class="show_min_people"></span></b> до <b><span class="show_max_people"></span></b> человек</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                                <button type="submit" class="btn btn-primary">Бронировать</button>
                              </div>
                        </div>
                      </form>
                  </div>
                </div>
              </div>
            </div>
           <!--modal-->
        </div>
      </div>
    <hr>
      <div class="row">
        <div class="col-md-12">
          <div id='calendar'></div>
        </div>
      </div>

    </main>
    <!--MAIN BODY-->
{% endblock %}

{% block js %}
    <!-- Datepicker -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- Timepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.min.js"></script>
    <!-- Select2 -->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script>
         document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');

        var calendar = new FullCalendar.Calendar(calendarEl, {

          headerToolbar: {
            left: 'dayGridMonth,timeGridWeek,timeGridDay',
            center: 'title',
            right: 'prev,next'
          },
          eventClick: function(info) {
            var eventObj = info.event;

            if (eventObj.url) {
              {#alert(#}
              {#  'Clicked ' + eventObj.title + '.\n' +#}
              {#  'Will open ' + eventObj.url + ' in a new tab'#}
              {#);#}
              window.open(eventObj.url, "_self");
              {#info.jsEvent.preventDefault(); // prevents browser from following link in current tab.#}
            } else {
              alert('Clicked ' + eventObj.title);
            }
          },
          initialDate: new Date(),
          events: [
          {% for i in order %}
              {
                  title: '{{ i.client }} / {{ i.sauna }}',
                  description: '{{ i.get_status_display }}',
                  start: '{{ i.start_time }}',
                  color: '{{ i.sauna.color }}',
                  url: "{% url 'order:each' i.pk %}",
              },
          {% endfor %}
          ]
        });

        calendar.render();
      });

           $(document).ready(function() {
                $( "#datepicker" ).datetimepicker({
                   dateFormat: 'yy-mm-dd',
               });
               $( "#datepicker1" ).datetimepicker({
                   dateFormat: 'yy-mm-dd',
               });
               $('.js-example-basic-single').select2({
                   style: ''
               });
               $('#select_3').select2({
                   dropdownParent: $('#exampleModal')
               })

               $('.people_count').on('input', function(){
                   let sauna_id = $('#sauna_select').val()
                   let people_number = $(this).val()
                   $.ajax({
                       url: '{% url "sauna:get_sauna_type_ajax" %}',
                       type: 'POST',
                        headers: {
                            'X-CSRFToken': csrftoken
                        },
                        data: JSON.stringify({
                            'sauna_id': sauna_id,
                        }),
                        contentType: 'application/json',
                        dataType: 'json',
                       success: function(data){
                           console.log(data)
                           for(let i=0; i < data.length; i++) {
                               let max = data[i]['fields']['max_people']
                               let min = data[i]['fields']['min_people']
                               if(people_number >= min && people_number <= max) {
                                   $('.show_sum_for_sauna').html(data[i]['fields']['price'])
                                   $('.show_min_people').html(min)
                                   $('.show_max_people').html(max)
                                   $('.show_sauna_price_info').removeClass('d-none')
                               }
                           }
                       },
                       error: function(error){
                           console.log(error)
                       },
                   })
               })
            });
        </script>
{% endblock %}

sauna/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
    <title>Klassik Elite SPA</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href='{% static "lib/main.css" %}' rel='stylesheet' />

    {% block css %}
    {% endblock %}

    <script>
        function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
const csrftoken = getCookie('csrftoken');
    </script>
</head>
<body>


<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container">
     <a class="navbar-brand" href="{% url 'sauna:calendar_view' %}">
      <img class="bg-white" src="{% static 'images/logo.png' %}" alt="" height="24">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sauna:calendar_view' %}">Календарь бронирование</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbar_" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Касса
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbar_">
                <li><a class="dropdown-item" href="{% url 'payment_log:list' %}">Касса</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'outlay:list' %}">Расходы</a></li>
            </ul>
        </li>
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             Заказы
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'order:list' %}">История заказов</a></li>
          </ul>
        </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Клиенты
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'client:list' %}">Все клиенты</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'client:add' %}">Добавить клиент</a></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex mb-2 mb-md-0">
         <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              {{ request.user.first_name }}
            </button>
            <ul class="dropdown-menu">
                {% if request.user.is_superuser %}
                    <li>
                        <a href="{% url 'admin:index' %}" class="dropdown-item">
                            Администрация
                        </a>
                    </li>
                    <li><hr class="dropdown-divider"></li>
                {% endif %}
                <li>
                  <a class="dropdown-item" href="{% url 'sauna:logout' %}">
                        Выйти
                  </a>
              </li>
            </ul>
          </div>
      </div>
    </div>
  </div>
</nav>


{% block body %}

{% endblock %}



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src='{% static "lib/main.js" %}'></script>
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->

{% block js %}

{% endblock %}
</body>
</html>

sauna/templates/signin.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Klassik Elite SPA</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/main.css' %}" rel="stylesheet">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

</head>
<body class="text-center">
  
  <div class="signin-div">
      <main class="form-signin">
        <form method="POST" action="{% url 'sauna:login' %}">
            {% csrf_token %}
          <img class="mb-4 img-fluid" src="{% static 'images/logo.png' %}" alt="" height="100">
          <h1 class="h3 mb-3 fw-normal">Пожалуйста войдите</h1>

          <div class="form-floating">
            <input type="text" name="login" class="form-control" id="floatingInput" placeholder=" ">
            <label for="floatingInput">Ваш логин</label>
          </div>
          <div class="form-floating">
            <input type="password" name="password" class="form-control" id="floatingPassword" placeholder=" ">
            <label for="floatingPassword">Пароль</label>
          </div>

          <div class="checkbox mb-3">
            <label>
              <input type="checkbox" name="remember_me" value="remember_me"> Запомнить меня
            </label>
          </div>
          <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
          <p class="mt-5 mb-3 text-muted">&copy; 2020–2021 Powered by DiamondSolutions</p>
        </form>
      </main>
  </div> 

</body>
</html>